name: turf_equality
description: Comparison of two GeoJSON objects, based on the turf pub-package
version: 0.0.2
repository: https://github.com/dartclub/turf_equality

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.19.3
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  analyzer: ^2.7.0
  benchmark: ^0.3.0

dependencies:
  turf: ^0.0.6